### ISSUE TITLE
Public key with repo

### ISSUE THREAD

**Issue by yagnik** [Shopify/ejson#15]
hey @burke what do you think about saving the public key with the repo? It's pretty hard to ask ops give you public key from databag everytime we want to update keys.

**Comment by burke** [comment]
It's stored at the top of ejson files as of 1.0.0. For example: https://github.com/Shopify/shopify/blob/master/config/secrets.production.ejson#L2

This way, you don't need the key to add secrets, you just `ejson encrypt <file>`.

**Comment by yagnik** [comment]
I did not notice that! THAT IS GENIUS! thank you
