### ISSUE TITLE
Support enryption for multiple public keys

### ISSUE THREAD

**Issue by Nirkus** [Shopify/ejson#21]
Hey,

would like to be able to encrypt the contents of a single ejson file for several public keys.
The idea is to have a list of keys in a git repo so that everyone is able to encrpt secret files for all of the keys and add the encrypted ejson to the git repo.

In the ejson file, the value of "_public_key" could be a list of public keys instead of a single key.
encrypt => encrypt for each key (encrypt symmetrically, encrypt symm. key for each public key)
decrypt => try to find the private key for any of the listed public keys and decypt

Any chance to have this supported?

**Comment by burke** [comment]
This sounds like a reasonable proposal, and it wouldn't add too much code complexity -- I would probably accept a PR for this, but I don't have any use for it myself or much spare time to work on ejson lately.

**Comment by domhdp** [comment]
(I get that this is a really old issue thread...but...) 

@Nirkus @burke 
Does anyone know if this ever got done? Multiple keys?

**Comment by lavoiesl** [comment]
AFAIK, no work has been done on this, but we’d be happy to review patches in that direction.

**Comment by thepwagner** [comment]
https://github.com/getsops/sops supports this.

EJSON operates on a single key by design.
