### ISSUE TITLE
Gem man page is not up-to-date with repo

### ISSUE THREAD

**Issue by OscarBarrett** [Shopify/ejson#22]
https://github.com/Shopify/ejson/blob/54b5a3a8f99170e32787b58aa0552e4edf5f5c6b/man/man1/ejson.1.ronn#L23

For the gem, under the OPTIONS section it says to set EJSON_KEYSDIR rather than EJSON_KEYDIR (KEY is incorrectly plural). This seems to be fixed in the repo though.

**Comment by burke** [comment]
I just pushed 1.0.1 with this and a few other fixes. Thanks!
