### ISSUE TITLE
Any Change Causes All Hashes to be Re-written

### ISSUE THREAD

**Issue by jeffutter** [Shopify/ejson#45]
Maybe I'm doing something funny here but the readme states

> Changes to secrets are auditable on a line-by-line basis with git blame.

However, if I decrypt my file, change a setting and re-encrypt it. Every line has changed.

My `git blame` shows everything changed by the last commit, not just the one thing I changed/added.

**Comment by burke** [comment]
Yup, you shouldn't be decrypting the file, just add new plaintext values to the encrypted file and encrypt it again.

**Comment by jeffutter** [comment]
Ahh, makes sense I guess. To change one, one would just delete the old encrypted value and add a new unencrypted one and re-encrypt the file?

**Comment by burke** [comment]
yup.

**Comment by jeffutter** [comment]
Awesome. Thanks for clarifying
