### ISSUE TITLE
Missing dev instructions

### ISSUE THREAD

**Issue by viraptor** [Shopify/ejson#47]
I wanted to fix one of the issues, but I got stuck for a long time just trying to get ejson to build. It would be great if there was a short section in the README about:

- what go version is expected
- how are the dependencies managed
- how to go from `git clone ...` on a completely clean host, to a built ejson binary

**Comment by noqcks** [comment]
I also ran into this problem. Would love some more documentation/build setups for non-shopify machines.

I don't think it's a bug either @catherinejones, more of an improvement.

**Comment by lavoiesl** [comment]
Better documentation would definitely be great; but in the mean time, you can interpret what is in https://github.com/Shopify/ejson/blob/master/dev.yml to get a sense of what is needed.

**Comment by burke** [comment]
Added basic CONTRIBUTING.md to master.
