### ISSUE TITLE
ejson prints non-errors to stderr

### ISSUE THREAD

**Issue by patrobinson** [Shopify/ejson#55]
In https://github.com/Shopify/ejson/commit/a385d6d5f9c642d29de684b8faa8568a9d8d3720 a change was made to print errors to stderr. It also changed the output for `encrypt` and `keygen` to also go to stderr. Since these are not errors they should probably go to stdout

**Comment by lavoiesl** [comment]
I agree for `keygen`, but the output of `encrypt` isn't data, it's more a log, so I’m not sure it belongs in stdout. Is this affecting your workflow?
