### ISSUE TITLE
Strings not interpolated

### ISSUE THREAD

**Issue by noqcks** [Shopify/ejson#60]
I installed via rubygem and get strings not being interpolated when encrypting.

```
➜  secrets git:(master) ejson encrypt env.dev.ejson
Wrote %d bytes to %s.
463env.dev.ejson⏎
```

**Comment by lavoiesl** [comment]
This was fixed in https://github.com/Shopify/ejson/pull/56 and released in v1.2.1, please update your gem or reopen this issue with the exact version you're experiencing the problem.

**Comment by noqcks** [comment]
@lavoiesl oh nice! 👌 

doesn't exist on rubygems though, [1.2.0](https://rubygems.org/gems/ejson/versions/1.2.0) is latest on RubyGems

**Comment by lavoiesl** [comment]
Mmm, that's unexpected. @burke ?

**Comment by burke** [comment]
Pushed now, sorry about that!
