### ISSUE TITLE
Changes from `1.1.0` to `v1.2.1`

### ISSUE THREAD

**Issue by Domon** [Shopify/ejson#62]
The latest version is `v1.2.1` while the last (and the only) entry in `CHANGELOG.md` is `1.1.0`.

Is there any breaking change between these versions?

Will `CHANGELOG.md` be updated?

Thanks! 🙏

**Comment by burke** [comment]
No breaking changes. I'll update the changelog later today.

**Comment by burke** [comment]
Done, sorry about that!
