### ISSUE TITLE
ejson encrypt command throws error - Windows

### ISSUE THREAD

**Issue by sundar-siv** [Shopify/ejson#83]
When I try to use ejson encrypt command I am getting below error

ejson command  : ejson encrypt <ejson file>

**C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/ejson-1.2.2/bin/ejson:2:in ``': No such file or directory - uname -sm (Errno::ENOENT)**

Platform - Windows 10
ejson version - 1.2.2

**Comment by thepwagner** [comment]
EJSON is not supported on windows.
